name: dmark
version: 0.0.1
author: Perry Birch
description: A benchmark library for dart.
homepage: https://github.com/Vizidrix/dmark
documentation: https://github.com/Vizidrix/dmark/tree/master/doc
dependencies:
  dfunct: any
dev_dependencies:
  unittest: any
